remote_theme: mmistakes/minimal-mistakes@4.17.2
plugins:
- jekyll-include-cache

locale: "en-US"
title: "Computational Biology in Western Montana"
name: "Genevieve Krause"
description: "A personal academic website demonstration"
url: "https://GenevieveKrause.github.io"
search: true
logo: "/assets/images/head.jpg"
teaser: "/assets/images/MT.jpg"
author:
name : "Genevieve Krause"
avatar : "/assets/images/head.jpg"
bio : "Computer Science Master's student at the University of Montana"
location : "UM"
