remote_theme: mmistakes/minimal-mistakes@4.17.2
plugins:
- jekyll-include-cache
minimal_mistakes_skin : "dirt"
layout: "single"

include: ["_data"]
include: ["_pages"]

# Site Settings
locale: "en-US"
title: "Computational Biology in Western Montana"
logo: "/assets/images/logo.jpg"
name: "Genevieve Krause"
description: "A personal academic website"
url: "https://GenevieveKrause.github.io"
search: "false"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true

# Site Author
author:
  name             : "Genevieve Krause"
  avatar           : "/assets/images/head.jpg"
  bio              : "Computer Science Master's student at the University of Montana"
  location         : "Missoula, MT"
  email            : "genevieve.krause@umontana.edu"
 
